### PR TITLE
Add support for @link tags

### PR DESCRIPTION
**Pull request by lumnn**
This adds support for `@link` tags.

In order to correctly parse php.net links correctly I had to add more characters to Parser::TAG constant regex.

Tests are running fine, so I hope it won't create.

_This is a part of the larger change set I'm planning to add to other repositories to be able to show links in the LSP hover popup._

image

### CODE REVIEW

**Comment by dantleech** [comment]
bonnus points if you can add a test to the existing tests

**Comment by lumnn** [comment]
I'll sort out the PHPStan issues from one of the checks and will see what I can do with tests

**Comment by lumnn** [comment]
Tests added as well fixed the PHPStan issues.

Good call as there was bug when `@link` has a label, which was not correctly parsed

**Comment by dantleech** [comment]
ach, looks like you need to run `php-cs-fixer` too. most repos in phpactor have a `composer integrate` target which runs all the checks.

**Comment by dantleech** [comment]
I'll fix the CS here :)

**Comment by lumnn** [comment]
Thanks.

I'll keep an eye on this, I've got IDE integration for that as well but I think I need to enable that per project, and I didn't do that here.

**Pull request merged**
